name: AT Test Workflow
on:
  workflow_dispatch:
jobs:
  list-val:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: at-ul/vault-workflows
          ref: main
          token: ${{ secrets.GH_PAT }}
