name: AT Test Workflow
on:
  workflow_dispatch:
jobs:
  list-val:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: at-ul/vault-workflows
          ref: main
          token: ${{ secrets.GH_PAT }}
          path: vault
      - name: run
        run: |
           ls -ltra ${GITHUB_WORKSPACE}/vault
           cat ${GITHUB_WORKSPACE}/vault/README.md
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: vault
          path: vault


  list-val2:
    runs-on: ubuntu-24.04
    needs: list-val
    steps:

      - name: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: vault
          path: vault
      - name: run
        run: |
           ls -ltra ${GITHUB_WORKSPACE}/vault
           cat ${GITHUB_WORKSPACE}/vault/README.md
  list-val3:
    runs-on: ubuntu-24.04
    needs: list-val
    steps:

      - name: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: vault
          path: vault
      - name: run
        run: |
           ls -ltra ${GITHUB_WORKSPACE}/vault
           cat ${GITHUB_WORKSPACE}/vault/README.md
