name: Invalidate Secret Workflow
on: workflow_dispatch
env:
  VAULT_CLUSTER_URL: http://18.206.203.244:8200/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"
  USER_NAME: "at-cli"

jobs:
  invalidate-secret:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check Token Creation Date
        run: |
          aws iam list-access-keys --user-name "${{ env.USER_NAME }}" \
          --query 'sort_by(AccessKeyMetadata[:2], &CreateDate)[*].[AccessKeyId, CreateDate]' --output text >> output.txt
          cat output.txt

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: at-ul
          minimum-approvals: 1
          exclude-workflow-initiator-as-approver: false

      - name: Delete older token
        run: |
          export key_id=$(awk 'NR==1 {print $1}' output.txt)
          echo $key_id
          aws iam delete-access-key --access-key-id=$key_id --user-name "${{ env.USER_NAME }}"
          rm output.txt
