name: Update Secret Workflow
on: workflow_dispatch
env:
  VAULT_CLUSTER_URL: http://18.206.203.244:8200/
jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check Token Count
        run: |
          key_count=$(aws iam list-access-keys --user-name at-cli \
          --query 'length(AccessKeyMetadata[])' --output text)
          if [["$key_count" -eq "2"]]; then
            echo "Error: Two active access keys found for application. Maximum of one active key is allowed." >&2
            exit 1
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
