name: Update Secret Workflow
on: workflow_dispatch
env:
  VAULT_CLUSTER_URL: http://18.206.203.244:8200/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"
  USER_NAME: "at-cli"
jobs:
  check-token-count:
    runs-on: ubuntu-latest
    steps:
      - name: Check Token Count
        run: |
          key_count=$(aws iam list-access-keys --user-name "${{ env.USER_NAME }}" \
          --query 'length(AccessKeyMetadata[])' --output text)
          if [[ "$key_count" == "2" ]]; then
            echo "Error: Two active access keys found for application. Maximum of one active key is allowed." >&2
            exit 1
          fi
  create-new-token:
    runs-on: ubuntu-latest
    steps:
      - name: Create new token
        run: |
          aws iam create-access-key --user-name "${{ env.USER_NAME }}" --output text >> output.txt

  write-token-to-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Write token to vault
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault
          vault version
          export VAULT_ADDR="${{ env.VAULT_CLUSTER_URL }}"
          echo $VAULT_CLUSTER_URL
          vault login -method=token -no-print=true "${{ secrets.VAULT_TOKEN }}"
          export key_id=$(awk '{print $2}' output.txt)
          export secret_key=$(awk '{print $4}' output.txt)
          vault kv put -mount=kv aws_keys access_key=$key_id secret_key=$secret_key
          rm output.txt
